<?php
// dozrmvr od hpzfrm
// Generated by issax_pi on Mon, 16 Oct 2023 19:10:22 +0600 in bunkernine
// Written successfully in C:/xampp/htdocs/Project/Astro
include $_SERVER["DOCUMENT_ROOT"]."/Server-picox.php";